# Generated by Django 5.1.1 on 2024-10-31 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_porfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Porfile",
            new_name="Profile",
        ),
    ]
