# Generated by Django 5.1.1 on 2024-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=250)),
                (
                    "weather",
                    models.IntegerField(
                        choices=[
                            (1, "Sunny"),
                            (2, "Rainy"),
                            (3, "Clody"),
                            (4, "Foggy"),
                            (5, "Snowy"),
                            (6, "Windy"),
                        ]
                    ),
                ),
                ("img", models.ImageField(upload_to="destinations/")),
                ("state", models.CharField(max_length=250)),
                ("district", models.CharField(max_length=250)),
                ("map_url", models.URLField(blank=True, max_length=2000)),
                ("description", models.TextField()),
            ],
        ),
    ]
